name = "mesprefs"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MESPREFS"
id = "fe6dd50fc08947a29fd4fb74a873e3e9"

[env.development]
vars = { SPOTIFY_PLAYLIST_ID = "", SPOTIFY_REDIRECT_URI = "http://localhost:8787/auth/callback" }

[env.production]
route = "api.mesprefs.com/*"
zone_id = ""
vars = { SPOTIFY_PLAYLIST_ID = "", SPOTIFY_REDIRECT_URI = "https://api.mesprefs.com/auth/callback" }
