name = "mesprefs"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.development]
vars = { SPOTIFY_PLAYLIST_ID = "" }

[env.production]
route = "api.mesprefs.com/*"
zone_id = ""
vars = { SPOTIFY_PLAYLIST_ID = "" }
